# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95174a3526aa0f3cef12c4f10af97919811210ab30e9ccc91e0d846b82b3b83904c581aad371a73782b225b53a74d091939d2c4a1afce1e584cae64aebf4ce0b

test:
  secret_key_base: fc7fcd7a6302d2b64d0cf99ca33eb338dcb64f840ecbbe0fc8d76ca982a58dfc59d0096b5d0ab6d0197710826e1e857a7988cea1cb2a0f34f00f36cb189c7a93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
